import json
import sqlite3
import os
from datetime import datetime
from mcp.server.fastmcp import FastMCP
from tavily import TavilyClient
from dotenv import load_dotenv

load_dotenv()

mcp = FastMCP("researchmind")
tavily = TavilyClient(api_key=os.getenv("TAVILY_API_KEY"))

def init_db():
    conn = sqlite3.connect("research.db")
    conn.execute("""
        CREATE TABLE IF NOT EXISTS research (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            topic TEXT,
            content TEXT,
            sources TEXT,
            timestamp TEXT
        )
    """)
    conn.commit()
    conn.close()

init_db()

@mcp.tool()
def web_search(query: str, max_results: int = 3) -> str:
    """Search the web for recent information. Use multiple times with different queries."""
    try:
        results = tavily.search(query, max_results=max_results)
        simplified = [
            {
                "title": r.get("title"),
                "url": r.get("url"),
                "content": r.get("content", "")[:300]  # truncate to 300 chars
            }
            for r in results.get("results", [])
        ]
        return json.dumps(simplified, indent=2)
    except Exception as e:
        return f"Search error: {str(e)}"

@mcp.tool()
def save_research(topic: str, content: str, sources: list = []) -> str:
    """Save research findings to the database for memory across sessions."""
    try:
        conn = sqlite3.connect("research.db")
        conn.execute(
            "INSERT INTO research (topic, content, sources, timestamp) VALUES (?, ?, ?, ?)",
            (topic, content, json.dumps(sources), datetime.now().isoformat())
        )
        conn.commit()
        conn.close()
        return "Research saved successfully."
    except Exception as e:
        return f"DB error: {str(e)}"

@mcp.tool()
def get_past_research(topic: str) -> str:
    """Check if we have already researched this topic before."""
    try:
        conn = sqlite3.connect("research.db")
        rows = conn.execute(
            "SELECT topic, content, sources, timestamp FROM research WHERE topic LIKE ? ORDER BY timestamp DESC LIMIT 2",
            (f"%{topic}%",)
        ).fetchall()
        conn.close()
        if not rows:
            return "No past research found on this topic."
        result = [{"topic": r[0], "content": r[1][:200], "timestamp": r[3]} for r in rows]
        return json.dumps(result, indent=2)
    except Exception as e:
        return f"DB error: {str(e)}"

@mcp.tool()
def generate_report(topic: str, findings: str, sources: list = []) -> str:
    """Format the final research into a clean markdown report."""
    timestamp = datetime.now().strftime("%B %d, %Y")
    sources_md = "\n".join([f"- {s}" for s in sources]) if sources else "- Sources embedded in findings"
    report = f"""# Meridian Research Report
## {topic}
*Generated by ResearchMind Agent — {timestamp}*

---

## Key Findings

{findings}

---

## Sources

{sources_md}

---
*Powered by Meridian MCP Agent | Built with LangGraph + Groq + Tavily*
"""
    return report

if __name__ == "__main__":
    mcp.run(transport="stdio")
